In [11]:
# 필요한 라이브러리 설치 및 임포트
!pip install pandas
!pip install lxml
import pandas as pd
import os
import glob
import re

# 컬럼 안의 문자열 최대 표시 길이 설정 (None이면 제한 없음)
pd.set_option('display.max_colwidth', None)
# 출력할 컬럼 개수 제한 해제
pd.set_option('display.max_columns', None)
# 출력할 행 개수 제한 해제
pd.set_option('display.max_rows', None)

Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.12/site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /opt/anaconda3/lib/python3.12/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.12/site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.12/site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: lxml in /opt/anaconda3/lib/python3.12/site-packages (5.3.0)

## 1. 학기별 개설교과목정보 데이터 합치기

In [12]:
files = glob.glob("data/*.xls")

all_data = []

for file in files:
    # HTML 테이블 읽기
    df = pd.read_html(file)[0]
    
    # 첫 번째 행을 컬럼명으로 지정
    df.columns = df.iloc[0]   # 0번 행을 컬럼명으로
    df = df.drop(index=0)     # 0번 행 삭제
    
    # 학기 정보 컬럼 추가
    semester = os.path.basename(file).replace("-sis.xls", "")
    df["개설학기정보"] = semester
    
    all_data.append(df)

# 모든 파일 병합
df_all = pd.concat(all_data, ignore_index=True)

df_all.head(3)

,학년도,학기,소속,학과,과목번호,분반,과목명,학점,수업시간/강의실,시간,교수진,수강생수,영어강의,중국어강의,승인과목,CU과목,홀짝구분,국제학생,Honors과목,공학인증,시험일자,수강대상,권장학년,수강신청 참조사항,과목 설명,비고,NaN,개설학기정보,HUSS과목,CI과목
0,2024 학년도,2학기,대학,게페르트국제학부,AAS1001,01,아시아학 개론,3.0,"화,목 12:00~13:15 [J107]",3.0,김소연,0000000048,O,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,전학년,1-4학년,NaN,NaN,NaN,2024-2,NaN,NaN
1,2024 학년도,2학기,대학,아트&테크놀로지학과,AAT2002,01,Humanities & creativity,3.0,월 13:30~16:15 [X514],3.0,정지수,0000000021,O,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,전학년,1-4학년,NaN,구) ANT2003,NaN,2024-2,NaN,NaN
2,2024 학년도,2학기,대학,아트&테크놀로지학과,AAT2003,01,Intro to Digital Arts,3.0,월 13:30~16:15 [X513],3.0,이형기,0000000031,O,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"2,3,4학년",1-4학년,NaN,구) ANT2004,NaN,2024-2,NaN,NaN

In [25]:
df_all.tail(3)

,학년도,학기,소속,학과,과목번호,분반,과목명,학점,수업시간/강의실,시간,교수진,수강생수,영어강의,중국어강의,승인과목,CU과목,홀짝구분,국제학생,Honors과목,공학인증,시험일자,수강대상,권장학년,수강신청 참조사항,과목 설명,비고,NaN,개설학기정보,HUSS과목,CI과목
9681,2026 학년도,1학기,대학,전인교육원,TLS1004,03,영어글로벌의사소통II,3.0,"화,목 09:00~10:15",3.0,"Bailey, Andrew",0000000000,O,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,전학년,1학년,NaN,영어II(고급)(COR1006)의 대체과목/영어II(COR1004)의 대체과목,"수강 대상 전학년, 절대평가",NaN,2026-1,NaN,NaN
9682,2026 학년도,1학기,대학,전인교육원,TLS1004,04,영어글로벌의사소통II,3.0,"화,목 10:30~11:45",3.0,"Bailey, Andrew",0000000000,O,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,전학년,1학년,NaN,영어II(고급)(COR1006)의 대체과목/영어II(COR1004)의 대체과목,"수강 대상 전학년, 절대평가",NaN,2026-1,NaN,NaN
9683,2026 학년도,1학기,대학,전인교육원,TLS1004,05,영어글로벌의사소통II,3.0,"화,목 16:30~17:45",3.0,"Kim, Jae Pil",0000000000,O,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,전학년,1학년,NaN,영어II(고급)(COR1006)의 대체과목/영어II(COR1004)의 대체과목,"수강 대상 전학년, 절대평가",NaN,2026-1,NaN,NaN

## 2. 필요한 열 선택

In [13]:
def make_major_df(df_all, codes=None, prefix=None):
    if codes is not None:
        df_major = df_all[df_all["과목번호"].isin(codes)]
    elif prefix is not None:
        df_major = df_all[df_all["과목번호"].str.startswith(prefix)]
    else:
        raise ValueError("codes 또는 prefix 중 하나를 지정해야 합니다.")

    result = []
    for code in df_major["과목번호"].unique():
        subset = df_major[df_major["과목번호"] == code]
        sems = ", ".join(sorted(subset["개설학기정보"].unique()))
        names = ", ".join(sorted(subset["과목명"].unique()))
        profs = ", ".join(sorted(subset["교수진"].dropna().unique()))
        result.append({
            "과목번호": code,
            "과목명": names,
            "교수": profs,
            "개설학기": sems
        })
    return pd.DataFrame(result)

## 3. 전공 데이터프레임 계절별로 만들기

In [14]:
def make_major_dfs(df_all, major_name, codes=None, prefix=None):
    import builtins

    # 정리된 전공 데이터프레임 생성
    df_major = make_major_df(df_all, codes=codes, prefix=prefix)
    builtins.__dict__[f"df_{major_name}"] = df_major

    # 계절별 데이터 생성
    builtins.__dict__[f"df_{major_name}_spring"] = df_major[df_major["개설학기"].str.contains("-1", na=False)]
    builtins.__dict__[f"df_{major_name}_fall"] = df_major[df_major["개설학기"].str.contains("-2", na=False)]
    builtins.__dict__[f"df_{major_name}_summer"] = df_major[df_major["개설학기"].str.contains("-summer", case=False, na=False)]
    builtins.__dict__[f"df_{major_name}_winter"] = df_major[df_major["개설학기"].str.contains("-winter", case=False, na=False)]

## 4. 계절별 전공 개설학기 보기

### 4-1. 연계전공

#### 4-1-1. 빅데이터사이언스 연계전공

In [15]:
bds_codes = [
    "STS2011", "MAT2110", "MAT3020", "MGT2002", "ECO2004", 
    "BDS4010", "CSW4010", "CSE4187",
    "AIC4012", "BDS3010", "BDS3020", "CSE4130", "CSW2010", "CSW2020",
    "CSW2030", "CSE3080", "CSW2050", "CSW3010", "CSE3081", "CSW3030", "CSE4110",
    "CSW3060", "CSW3080",
    "CSW4020", "ECO2009", "ECO3022", "ECO3023", "ECO4003", "ECO4004",
    "ECO4032", "EEE4178", "JAS4014", "MAS1004", "MAS2009",
    "MAS2010", "MAT3110", "MAT4331", "MGT4202", "MGT4208", "MGT4226",
    "MGT4515", "MGT4517", "MGT6613", "MGTG613"
]

make_major_dfs(df_all, major_name="bds", codes=bds_codes)

In [16]:
df_bds_spring
#df_bds_summer
# df_bds_fall
#df_bds_winter

,과목번호,과목명,교수,개설학기
1,BDS4010,빅데이터종합설계(캡스톤디자인),"최수진, 하정욱","2023-2, 2024-2, 2025-2, 2026-1"
2,CSE3080,자료구조,"소정민, 양지훈, 장부루, 장형수, 정성원, 정영민, 최준석","2023-1, 2023-2, 2024-1, 2024-2, 2024-summer, 2024-winter, 2025-1, 2025-2, 2025-summer, 2025-winter, 2026-1"
3,CSE3081,알고리즘설계와분석,"김세준, 서양진, 소정민, 임인성, 장형수","2023-1, 2023-2, 2024-2, 2025-2, 2025-summer, 2026-1"
4,CSE4187,"산학프로젝트(캡스톤디자인), 캡스톤디자인II(캡스톤디자인)","구명완, 장두성, 정영민","2023-1, 2023-2, 2024-1, 2024-2, 2025-1, 2025-2, 2026-1"
9,ECO2004,경제통계학,"김세진, 김인경, 박경옥, 백예인, 사공용, 오민석, 이성원, 이영훈, 주하연","2023-1, 2023-2, 2023-winter, 2024-1, 2024-2, 2024-winter, 2025-1, 2025-2, 2025-winter, 2026-1"
10,ECO2009,계량경제학I,"김재호, 남준우, 백예인, 이성원, 이영훈, 이한식","2023-1, 2023-2, 2024-1, 2024-2, 2025-1, 2025-2, 2026-1"
11,ECO3022,금융시장의빅데이터분석(캡스톤디자인),정재식,"2023-2, 2024-2, 2025-2, 2026-1"
14,MAS1004,Data&AI,"김태훈, 남현우, 사영준, 정다샘, 정해동","2023-1, 2023-2, 2024-1, 2024-2, 2024-winter, 2025-1, 2025-2, 2026-1"
15,MAT2110,선형대수학,"강유태, 김대욱, 김준태, 박준용, 안소영, 옥지훈, 이영란, 임경필, 조상현, 조성희, 조장현, 최미란, 최승일, 한상현","2023-1, 2023-2, 2023-summer, 2023-winter, 2024-1, 2024-2, 2024-summer, 2024-winter, 2025-1, 2025-2, 2025-summer, 2025-winter, 2026-1"
16,MAT3020,통계학입문,"임경수, 임경필","2023-1, 2023-2, 2023-summer, 2023-winter, 2024-1, 2024-2, 2024-summer, 2024-winter, 2025-1, 2025-2, 2025-summer, 2026-1"
18,MGT2002,경영통계학,"김명석, 김범수, 이군희, 이윤동, 정예숙, 조성빈","2023-1, 2023-2, 2023-summer, 2023-winter, 2024-1, 2024-2, 2024-summer, 2024-winter, 2025-1, 2025-2, 2025-summer, 2025-winter, 2026-1"
19,MGT4202,통계자료분석,이군희,"2023-1, 2023-2, 2024-1, 2024-2, 2025-1, 2025-2, 2026-1"
21,MGTG613,인공지능 자료분석,이윤동,"2024-2, 2025-2, 2026-1"
22,STS2011,기초빅데이터프로그래밍,서경희,"2023-1, 2023-2, 2024-1, 2024-2, 2025-1, 2025-2, 2026-1"
23,BDS3010,빅데이터컴퓨팅,"문현아, 서경희","2023-1, 2024-1, 2025-1, 2026-1"
24,CSE4110,데이터베이스시스템,정성원,"2023-1, 2024-1, 2025-1, 2026-1"
25,CSE4130,기초머신러닝,"박운상, 최준석","2023-1, 2024-1, 2025-1, 2026-1"
26,CSW2010,기초C언어,"강호석, 서양진, 장나은","2023-1, 2024-1, 2025-1, 2026-1"
27,CSW3010,알고리즘입문,임종석,"2023-1, 2024-1, 2025-1, 2026-1"
28,CSW3060,빅데이터학,홍정하,"2023-1, 2024-1, 2025-1, 2026-1"
29,CSW3080,빅데이터마이닝입문,박석,"2023-1, 2024-1, 2025-1, 2026-1"
30,CSW4020,정보처리및자연언어처리,홍정하,"2023-1, 2024-1, 2025-1, 2026-1"
31,ECO3023,AI금융(캡스톤디자인),정재식,"2023-1, 2024-1, 2025-1, 2026-1"
32,ECO4004,경제수리통계학,"남준우, 이성원","2023-1, 2025-1, 2026-1"
33,ECO4032,금융시장계량분석(캡스톤디자인),김재호,"2023-1, 2024-1, 2025-1"
34,MAT3110,이산수학,"조성희, 조창연, 최승일","2023-1, 2024-1, 2025-1, 2026-1"
35,MGT4226,빅데이터와 비즈니스 모델,김진화,"2024-1, 2025-1"
36,MGT4515,빅데이터기반마케팅과스타트업,정재학,"2023-2, 2025-1"
37,MAS2010,Fundamentals of Computer Science for Korean Studies,조은경,2023-1
38,MGT4517,메타버스가상시장과마케팅사이언스,정재학,2023-1

#### 4-1-2. 공공인재 연계전공

In [17]:
pub_codes = [
    "PUB2005", "POL3130", "POL2002", "SOC2001", "SOC2003", "SOC3010",
    "ECO2001", "ECO2002", "ECO3009", "ECO3011", "ECO3017", "MGT2002", 
    "MGT2003", "PHI2005", "PSY2001", "PSY3009", "PUB3030", "PUB3016",
    "PUB3029", "PUB3023", "PUB3024", "PUB3025", "PUB3031", "PUB3032",
    "PUB3026", "PUB3021", "PUB3020", "PUB3022", "PUB3028", "PUB3027",
    "PUB4009", "KOR4500", "EDU2001", "PHI4010", "ECO2007", "MGT3004",
    "MGT4301", "MGT3005", "MGT4404"
]

make_major_dfs(df_all, major_name="pub", codes=pub_codes)

In [ ]:
df_pub_spring
#df_pub_summer
#df_pub_fall
#df_pub_winter

,과목번호,과목명,교수,개설학기
0,ECO2001,경제학원론I,"Iris Haydar Doruk, 김경환, 김숙영, 김영철, 김진원, 김홍균, 손성빈, 신혜선, 안태현, 이재철, 이진권, 전현배, 주하연, 허정","2023-1, 2023-2, 2023-summer, 2023-winter, 2024-1, 2024-2, 2024-summer, 2024-winter, 2025-1, 2025-2, 2025-summer, 2025-winter, 2026-1"
1,ECO2002,경제학원론II,"곽노선, 김경환, 김숙영, 김재호, 김형욱, 송의영, 우수경, 전현배, 정국모, 허준영","2023-1, 2023-2, 2023-summer, 2023-winter, 2024-1, 2024-2, 2024-summer, 2024-winter, 2025-1, 2025-2, 2025-summer, 2025-winter, 2026-1"
2,ECO2007,거시경제학I,"곽노선, 곽준희, 김숙영, 김형욱, 남주하, 이윤수, 정국모, 조윤호, 허준영","2023-1, 2023-2, 2024-1, 2024-2, 2025-1, 2025-2, 2026-1"
3,ECO3011,국제금융론,"곽준희, 김윤정","2023-1, 2023-2, 2024-1, 2024-2, 2025-2"
4,ECO3017,국제경제학,"곽준희, 김윤정","2023-1, 2023-2, 2024-1, 2024-2, 2025-1, 2026-1"
5,EDU2001,교육학개론,"김재웅, 신효정, 이예경","2023-1, 2023-2, 2024-1, 2024-2, 2025-1, 2025-2"
6,MGT2002,경영통계학,"김명석, 김범수, 이군희, 이윤동, 정예숙, 조성빈","2023-1, 2023-2, 2023-summer, 2023-winter, 2024-1, 2024-2, 2024-summer, 2024-winter, 2025-1, 2025-2, 2025-summer, 2025-winter, 2026-1"
7,MGT2003,회계학원론,"강평경, 김민, 김아람, 박두리, 박재형, 변상혁, 송민섭, 양준선, 이다혜, 천준범","2023-1, 2023-2, 2023-summer, 2023-winter, 2024-1, 2024-2, 2024-summer, 2024-winter, 2025-1, 2025-2, 2025-summer, 2025-winter, 2026-1"
8,MGT3004,재무관리,"김도성, 박영석, 안성필, 오동석, 이상호, 이영주, 이정진, 홍광헌","2023-1, 2023-2, 2024-1, 2024-2, 2025-1, 2025-2, 2025-summer, 2025-winter, 2026-1"
9,MGT3005,관리회계,"김민, 박예연, 박재형, 변상혁, 양준선, 이종운, 황국재","2023-1, 2023-2, 2024-1, 2024-2, 2025-1, 2025-2, 2026-1"
10,MGT4301,투자론,"김도성, 박영석, 안성필, 홍광헌","2023-1, 2023-2, 2024-1, 2024-2, 2025-1, 2025-2, 2026-1"
11,MGT4404,원가회계,"박예연, 양준선, 황국재","2023-1, 2023-2, 2024-1, 2024-2, 2025-1, 2025-2, 2026-1"
12,POL2002,정치학개론,"김태심, 이현우, 조영호, 하상응, 한영빈","2023-1, 2023-2, 2023-summer, 2024-1, 2024-2, 2024-summer, 2025-1, 2025-2, 2026-1"
13,PSY2001,일반심리학,"김근영, 나진경, 정유선, 홍승범","2023-1, 2023-2, 2024-1, 2024-2, 2025-1, 2025-2, 2026-1"
14,PUB3020,경제법,"송태원, 이나정, 홍대식","2023-2, 2024-2, 2025-2, 2026-1"
15,PUB3022,노동법,심재진,"2023-2, 2024-2, 2025-2"
16,PUB3024,"민법 Ⅱ (채권총칙,채권각칙,가족법)","박진완, 이승기, 이창현","2023-2, 2024-2, 2025-2"
17,PUB3027,세법,"김상훈, 김상훈, 남미영, 조병호","2023-2, 2024-2, 2025-2"
18,PUB3028,지식재산권법,"김미화, 박준우","2023-2, 2024-2, 2025-2"
19,PUB3029,행정법,임성훈,"2023-2, 2024-2, 2025-2"
20,PUB3032,형사소송법,"곽정기, 김연진","2023-2, 2024-2, 2025-2"
21,PUB4009,국제인권과법,이상수,"2023-2, 2024-2, 2025-2"
22,SOC2001,사회학개론,"김경만, 김영수, 김우선, 민병교, 이현숙","2023-1, 2023-2, 2023-winter, 2024-1, 2024-2, 2024-summer, 2025-1, 2025-2, 2026-1"
23,PHI2005,논리학개론,오은영,"2023-1, 2023-summer, 2023-winter, 2024-1, 2024-summer, 2024-winter, 2025-1, 2025-2, 2025-summer"
24,PSY3009,사회심리학,김진형,"2023-1, 2024-1, 2025-1, 2025-2"
36,SOC3010,사회발전론,김영수,2023-2

#### 4-1-3. 교직

In [19]:
edu_codes = [
    "EDU2001", "EDU2002", "EDU2003", "EDU2004", "EDU3001", "EDU3047",
    "EDU3002", "EDU3033", "EDU3045", "EDU3046", "EDU3037", "EDU3004", "EDU3035",
    "EDU2005", "EDU2007", "EDU3038", "EDU3039", "EDU3048", "EDU3049",
    "SHU4019", "SHU4022", "SHU4031", "EDU3036"
]

make_major_dfs(df_all, major_name="edu", codes=edu_codes)

In [20]:
df_edu_spring
#df_edu_summer
#df_edu_fall
#df_edu_winter

,과목번호,과목명,교수,개설학기
0,EDU2001,교육학개론,"김재웅, 신효정, 이예경","2023-1, 2023-2, 2024-1, 2024-2, 2025-1, 2025-2"
1,EDU2002,교육철학및교육사,한석훈,"2023-1, 2023-2, 2024-1, 2024-2, 2025-1, 2025-2, 2026-1"
2,EDU2003,교육심리,"김명숙, 양미경, 이예경","2023-2, 2024-2, 2025-1, 2026-1"
4,EDU3035,교육봉사활동,"신효정, 양미경","2023-1, 2023-2, 2023-summer, 2023-winter, 2024-1, 2024-2, 2024-summer, 2024-winter, 2025-1, 2025-2, 2025-summer, 2025-winter, 2026-1"
5,EDU3037,생활지도및상담,"계은경, 한기백","2023-1, 2023-2, 2024-1, 2024-2, 2025-1, 2025-2, 2026-1"
6,EDU3045,특수교육학개론,박미경,"2023-1, 2023-2, 2024-1, 2024-2, 2025-1, 2025-2, 2026-1"
7,EDU3046,교직실무,"김연후, 김재웅, 이미숙","2023-1, 2024-2, 2025-2"
9,EDU2004,교육방법및교육공학,"신소영, 양미경","2023-1, 2024-1, 2025-1"
10,EDU3002,교육행정및교육경영,"김재웅, 김정현","2023-1, 2024-1, 2025-1, 2026-1"
11,EDU3049,AI활용교육의이론과실제,신효정,"2023-1, 2024-1, 2025-1, 2026-1"
12,EDU3001,교육과정,양미경,"2023-1, 2024-1, 2025-2, 2026-1"
13,EDU3047,교육평가,"신효정, 이예경","2023-1, 2024-1, 2026-1"
14,SHU4019,삶과교육,양미경,"2023-2, 2025-2, 2026-1"

#### 4-1-4. 스포츠미디어

In [24]:
spm_codes = [
    # 커뮤니케이션 분야
    "MAE3014", "MAS2004", "MAE3001", "MAS3001", 
    "JAS3001", "JAS3012", "JAS3005", "JAS4015", "JAS4014", "JAS3002", 
    "JAS3007", "JAS2008", "JAS4011", "JAS3010", 
    "MAE2001", "MAE3002", "MAE3003", "MAE3009", "MAE3035",
    # 스포츠 이론 분야
    "SPM3001", "SPM3004", "SPM3005", "SPM3006", "SPM3007", "SPM3008", "SPM3009", "SPM3010", "SPM3010", "SPM3011", "SPM3012", "SPM3013", "SPM3014", "SPM3015",
    # 스포츠 실기 분야
    "SPM3101", "SPM3102", "SPM3103", "SPM3104", "SPM3105", "SPM3106", "SPM3107", "SPM3108", "SPM3110", "SPM3111", "SPM3112", "SPM3113", "SPM3114", "SPM3115", "SPM3116", "SPM3117", "SPM3118", "SPM3119", "SPM3120",
]

make_major_dfs(df_all, major_name="spm", codes=spm_codes)

In [29]:
df_spm_spring
#df_spm_summer
#df_spm_fall
#df_spm_winter

,과목번호,과목명,교수,개설학기
0,JAS3007,광고4.0,"유현재, 윤각","2023-1, 2023-2, 2024-1, 2024-2, 2025-1, 2025-2, 2026-1"
3,MAE2001,미디어&엔터테인먼트개론,"김군주, 이수영","2023-1, 2024-1, 2024-2, 2025-1, 2025-2, 2026-1"
4,MAE3009,미디어엔터테인먼트조직과산업의이해,조재희,"2023-1, 2024-2, 2025-2"
5,MAE3014,커뮤니케이션학입문,"ZHOU, NAN, ZHOUNAN, 조재희","2023-1, 2023-2, 2024-1, 2024-2, 2025-1, 2025-2, 2026-1"
6,MAS2004,인간소통과미디어,"나은영, 임인재","2023-1, 2023-2, 2024-1, 2024-2, 2025-1, 2025-2, 2026-1"
7,MAS3001,"미디어커뮤니케이션조사론, 미디어커뮤니케이션조사론(중국어강의)","JIN XIANMEI, ZHOU, NAN, ZHOUNAN, 김수연, 김정현, 민병운, 유민진, 육은희, 정수린, 조재희","2023-1, 2023-2, 2023-summer, 2024-1, 2024-2, 2024-winter, 2025-1, 2025-2, 2025-summer, 2025-winter, 2026-1"
11,SPM3101,"스쿠바다이빙, 스쿠버다이빙",민우식,"2023-1, 2023-2, 2024-1, 2024-2, 2024-summer, 2025-1, 2025-2, 2026-1"
12,SPM3104,필드골프I,"신은철, 최대혁","2024-1, 2024-2, 2025-1, 2025-2"
13,SPM3106,체력트레이닝,"소위영, 안현균, 조형식, 최대혁","2023-1, 2023-2, 2023-summer, 2023-winter, 2024-1, 2024-2, 2024-summer, 2024-winter, 2025-1, 2025-2, 2025-summer, 2026-1"
14,SPM3110,라켓볼,최대혁,"2023-2, 2024-2, 2025-1, 2025-2, 2026-1"
15,SPM3111,참선,정용철,"2023-1, 2023-2, 2024-1, 2024-2, 2025-1"
18,SPM3119,파워요가,장영진,"2023-1, 2024-1, 2024-2, 2025-2, 2026-1"
19,SPM3120,댄스피트니스,장영진,"2023-1, 2023-2, 2024-1, 2024-2, 2025-1, 2025-2, 2026-1"
20,JAS3001,저널리즘개론,"김균, 서수민, 이경미, 임종섭","2023-1, 2024-1, 2025-1, 2025-winter, 2026-1"
21,JAS3005,대중문화론,홍성일,"2024-1, 2025-1"
22,JAS4011,마케팅커뮤니케이션과시장읽기,이재진,2025-1
23,MAE3002,"미디어,인간,사회",김정현,"2023-1, 2024-1, 2025-1, 2025-2"
24,MAE3003,미디어심리학,나은영,"2023-2, 2024-1, 2025-1, 2025-2"
25,SPM3007,스포츠사회학,안현균,"2023-1, 2024-1, 2025-1, 2026-1"
26,SPM3010,스포츠산업론,이명선,"2023-1, 2024-1, 2025-1, 2026-1"
27,SPM3011,스포츠생리학,김태형,"2023-1, 2024-1, 2025-1, 2026-1"
28,SPM3014,스포츠소비자행동론,이명선,"2023-1, 2024-1, 2025-1, 2026-1"
29,SPM3108,호신술I,고영정,"2023-1, 2024-1, 2025-1, 2026-1"
30,SPM3114,댄스스포츠II,"김대동, 김수미","2023-1, 2024-1, 2025-1, 2026-1"
31,MAE3001,매스커뮤니케이션,박상희,"2023-1, 2024-1"
32,SPM3015,서사적체육:스포츠와스토리텔링,정용철,"2023-1, 2025-2"
37,SPM3105,필드골프II,신은철,2026-1

### 4-2. 일반 전공

#### 4-2-1. 경영

In [30]:
make_major_dfs(df_all, major_name="mgt", prefix="MGT")

In [31]:
df_mgt_spring
#df_mgt_summer
#df_mgt_fall
#df_mgt_winter

,과목번호,과목명,교수,개설학기
0,MGT2002,경영통계학,"김명석, 김범수, 이군희, 이윤동, 정예숙, 조성빈","2023-1, 2023-2, 2023-summer, 2023-winter, 2024-1, 2024-2, 2024-summer, 2024-winter, 2025-1, 2025-2, 2025-summer, 2025-winter, 2026-1"
1,MGT2003,회계학원론,"강평경, 김민, 김아람, 박두리, 박재형, 변상혁, 송민섭, 양준선, 이다혜, 천준범","2023-1, 2023-2, 2023-summer, 2023-winter, 2024-1, 2024-2, 2024-summer, 2024-winter, 2025-1, 2025-2, 2025-summer, 2025-winter, 2026-1"
2,MGT3001,조직행동이론,"양동훈, 이인석, 이해경, 장영균, 조봉순, 최장호","2023-1, 2023-2, 2024-1, 2024-2, 2025-1, 2025-2, 2026-1"
3,MGT3002,경영정보시스템,"김용진, 김태연, 백헌, 오혜림, 이상근, 한재형","2023-1, 2023-2, 2024-1, 2024-2, 2025-1, 2025-2, 2026-1"
4,MGT3003,"생산관리론, 운영관리","강세원, 김길선, 김민균, 김민주, 김수효, 하병천","2023-1, 2023-2, 2024-1, 2024-2, 2024-summer, 2025-1, 2025-2, 2025-winter, 2026-1"
5,MGT3004,재무관리,"김도성, 박영석, 안성필, 오동석, 이상호, 이영주, 이정진, 홍광헌","2023-1, 2023-2, 2024-1, 2024-2, 2025-1, 2025-2, 2025-summer, 2025-winter, 2026-1"
6,MGT3005,관리회계,"김민, 박예연, 박재형, 변상혁, 양준선, 이종운, 황국재","2023-1, 2023-2, 2024-1, 2024-2, 2025-1, 2025-2, 2026-1"
7,MGT3006,마케팅원론,"김주영, 김채영, 김태민, 박경도, 박세훈, 성연진, 이민경, 전성률, 정재학, 조혜원","2023-1, 2023-2, 2024-1, 2024-2, 2025-1, 2025-2, 2026-1"
8,MGT3007,국제경영론,"Song, Sangcheol, 강리브가, 김도의, 김창수, 박영수, 이강표, 정라미, 정선욱","2023-1, 2023-2, 2023-summer, 2024-1, 2024-2, 2025-1, 2025-2, 2026-1"
9,MGT3008,전공진로설계Ⅰ,"김진화, 양준선, 장영균, 정선욱, 하병천","2024-1, 2024-2"
10,MGT4102,경영전략,"김양민, 김윤진, 박종훈, 서정일, 이승혜","2023-1, 2023-2, 2023-summer, 2023-winter, 2024-1, 2024-2, 2024-summer, 2024-winter, 2025-1, 2025-2, 2025-summer, 2025-winter, 2026-1"
11,MGT4103,조직구조와전략,김양민,"2023-2, 2024-2, 2025-1"
12,MGT4104,리더쉽이론,이인석,"2023-1, 2023-2, 2024-2, 2025-1, 2025-2, 2026-1"
13,MGT4105,기업윤리,장영균,"2023-1, 2023-2, 2024-1, 2024-2, 2025-1, 2025-2, 2026-1"
14,MGT4106,인적자원관리,"양동훈, 조봉순, 최장호","2023-1, 2023-2, 2024-1, 2024-2, 2025-1, 2025-2, 2026-1"
15,MGT4201,의사결정론,"김범수, 민재형, 조성빈","2023-1, 2023-2, 2024-1, 2024-2, 2025-1, 2025-2, 2026-1"
16,MGT4202,통계자료분석,이군희,"2023-1, 2023-2, 2024-1, 2024-2, 2025-1, 2025-2, 2026-1"
17,MGT4203,경영과학,"김범수, 민재형, 이윤동, 정철우, 조성빈","2023-1, 2023-2, 2024-1, 2024-2, 2025-1, 2025-2, 2026-1"
19,MGT4221,경영과정보기술,김아현,"2024-2, 2025-1, 2025-2, 2026-1"
20,MGT4222,모바일통신경영,이상근,"2023-1, 2024-2, 2025-2"
22,MGT4227,디지털변혁과비즈니스모델혁신,김용진,"2023-2, 2024-1, 2024-2, 2025-1, 2025-2, 2026-1"
23,MGT4231,인공지능과경영모델,김진화,"2023-1, 2024-1, 2024-2, 2025-1, 2025-2, 2026-1"
24,MGT4241,기술경영과기술사업화,"박수현, 백서현","2023-1, 2023-2, 2024-1, 2024-2, 2025-1, 2025-2, 2026-1"
25,MGT4247,공급체인관리와e-business,김민균,"2023-1, 2023-2, 2024-1, 2024-2, 2025-1, 2025-2, 2026-1"
26,MGT4248,비즈니스프로세스관리,이준겸,"2023-1, 2023-2, 2024-1, 2024-2, 2025-1, 2025-2, 2026-1"
28,MGT4301,투자론,"김도성, 박영석, 안성필, 홍광헌","2023-1, 2023-2, 2024-1, 2024-2, 2025-1, 2025-2, 2026-1"
29,MGT4303,파생상품론,"안성필, 원재환, 이정진","2023-1, 2023-2, 2024-1, 2024-2, 2025-1, 2025-2, 2026-1"
30,MGT4304,포트폴리오관리,이영주,"2023-1, 2023-2, 2024-1, 2024-2, 2025-2"
31,MGT4306,금융리스크관리,원재환,"2023-1, 2023-2, 2024-1, 2024-2, 2025-2, 2026-1"
32,MGT4307,금융기관론,이상호,"2023-1, 2023-2, 2024-1, 2024-2, 2025-1, 2025-2, 2026-1"
33,MGT4316,금융위기와 금융산업 혁신,이상호,"2023-2, 2024-1, 2024-2, 2025-1, 2025-2, 2026-1"
34,MGT4331,보험학원론,최정호,"2023-1, 2023-2, 2024-1, 2024-2"
35,MGT4401,중급회계1,"강평경, 김아람, 송민섭, 이다혜","2023-1, 2023-2, 2024-1, 2024-2, 2025-1, 2025-2, 2026-1"
36,MGT4402,중급회계2,"박두리, 박재형, 송민섭","2023-1, 2023-2, 2024-1, 2024-2, 2025-1, 2025-2, 2026-1"
37,MGT4404,원가회계,"박예연, 양준선, 황국재","2023-1, 2023-2, 2024-1, 2024-2, 2025-1, 2025-2, 2026-1"
40,MGT4516,인공지능과마케팅,김주영,"2023-2, 2024-2, 2025-1, 2025-2"
41,MGT4601,기업과국제환경,"김유진, 김장순, 배준영","2023-1, 2024-1, 2024-2, 2025-1, 2025-2, 2026-1"
43,MGT4605,무역경영관리,손명옥,"2023-2, 2024-1, 2024-2, 2025-1, 2025-2, 2026-1"
46,MGT4712,"지식,인성그리고경영","김창수, 이정진","2023-1, 2024-2"
47,MGT4719,서비스 공급망관리와 ESG,"김민균, 김민주","2024-1, 2024-2, 2025-1, 2026-1"
49,MGT4724,해외진출 한국기업의 현지화전략(탐구공동체),정선욱,"2024-2, 2025-1"
50,MGTG505,브랜드전략론,전성률,"2024-1, 2024-2"
51,MGTG613,인공지능 자료분석,이윤동,"2024-2, 2025-2, 2026-1"
53,MGT4101,경영전략시뮬레이션,박종훈,"2023-1, 2024-1, 2025-1"
54,MGT4204,시뮬레이션,"민재형, 정철우","2023-1, 2024-1, 2025-1, 2025-2, 2026-1"
55,MGT4206,경영환경에서의시계열자료분석과예측(캡스톤디자인),김명석,"2023-2, 2024-1, 2025-1, 2026-1"
56,MGT4226,빅데이터와 비즈니스 모델,김진화,"2024-1, 2025-1"
57,MGT4243,경영품질의이해,강세원,"2023-1, 2024-1, 2025-1, 2026-1"
58,MGT4403,고급회계,송민섭,"2023-1, 2025-1, 2026-1"
59,MGT4407,회계감사,천준범,"2023-1, 2024-1, 2025-1"
60,MGT4501,마케팅전략,김태민,"2023-2, 2024-1, 2025-1"
61,MGT4503,시장조사론,"박경도, 박세훈","2023-1, 2023-2, 2025-1, 2026-1"
62,MGT4515,빅데이터기반마케팅과스타트업,정재학,"2023-2, 2025-1"
63,MGT4604,국제경영전략,"김장순, 김창수","2023-1, 2023-2, 2024-1, 2025-1, 2026-1"
64,MGT4616,글로벌 혁신 전략,강리브가,"2023-1, 2024-1, 2025-1, 2026-1"
65,MGT4718,이해관계자자본주의와ESG,박영석,"2023-1, 2024-1, 2025-1, 2025-2"
66,MGTG610,경영 데이터사이언스,"이윤동, 조성빈","2025-1, 2025-2"
67,MGTG707,ESG 세미나,송민섭,2025-1
68,MGT4207,BA 인공지능,이윤동,"2023-1, 2023-2, 2024-1"
69,MGT4313,벤처와금융시장(캡스톤디자인),정유신,2023-1
70,MGT4508,서비스마케팅,"김채영, 이민경","2023-1, 2023-2, 2025-2"
71,MGT4513,마케팅최신주제및사례연구,하영원,2023-1
72,MGT4517,메타버스가상시장과마케팅사이언스,정재학,2023-1
73,MGT4701,경영영어라이팅,김이권,"2023-1, 2023-2, 2024-1"
76,MGT4107,노사관계론,양동훈,"2024-1, 2025-2"
77,MGT4502,소비자행동론,"성연진, 조혜원, 하영원","2023-2, 2024-1, 2025-2"
78,MGT4510,국제마케팅론,"김도의, 이철","2023-winter, 2024-1, 2024-winter, 2025-2"
79,MGT4511,마케팅관리,서민지,"2025-2, 2026-1"
80,MGT4609,외환론,이강표,"2025-2, 2026-1"
83,MGTG315,"메타버스가상시장과마케팅(캡스톤디자인), 빅테크 가상 시장과 하이테크 마케팅",정재학,"2024-1, 2025-2"
85,MGT4245,정보화시대의기업경영과혁신,구자현,"2023-2, 2024-1"
86,MGTG109,기업지배구조와기업전략,서정일,"2023-2, 2024-1, 2026-1"
87,MGTG310,가치평가이론과실무,안성필,2024-1
90,MGT4252,글로벌 공급망과 리스크 관리,김민균,2026-1
91,MGT4518,혁신 기술과 신시장 마케팅 전략,정재학,2026-1
92,MGT4723,인공지능 활용 비즈니스 모델링(탐구공동체),김명석,2026-1

#### 4-2-2. 국문

In [32]:
make_major_dfs(df_all, major_name="kor", prefix="KOR")

In [33]:
df_kor_spring
#df_kor_summer
#df_kor_fall
#df_kor_winter

,과목번호,과목명,교수,개설학기
0,KOR2001,국어학입문,"이정훈, 이지영","2023-1, 2023-2, 2024-1, 2024-2, 2025-1, 2025-2, 2026-1"
1,KOR2200,국문학개설,"백진우, 이정원, 황윤정","2023-1, 2023-2, 2024-1, 2024-2, 2025-1, 2025-2, 2026-1"
2,KOR2201,문학이란무엇인가,"김경수, 박숙자, 박슬기, 우찬제","2023-1, 2023-2, 2024-1, 2024-2, 2025-1, 2025-2, 2026-1"
4,KOR3015,국어사,이지영,"2023-1, 2024-2, 2026-1"
8,KOR3402,현대소설텍스트읽기I,김경수,"2023-1, 2024-2"
11,KOR4300,고전문학연습,"백진우, 황윤정","2023-1, 2024-2, 2026-1"
12,KOR4501,언어와컴퓨터,황화상,"2023-1, 2024-2"
13,KOR4504,문학과문화콘텐츠,"김예람, 박미란","2023-1, 2023-2, 2024-1, 2024-2, 2025-1, 2025-2, 2026-1"
15,KORQ982,국어교과논리및논술,"강효경, 주세형","2023-2, 2024-2, 2025-2, 2026-1"
16,KORQ983,국어교과교재연구및지도법,"강효경, 주세형","2023-2, 2024-2, 2025-2, 2026-1"
17,KOR3002,국어음운론,김한별,"2023-1, 2025-1, 2026-1"
18,KOR3005,국어의미론,"명정희, 이정훈","2023-1, 2024-1, 2025-1, 2026-1"
19,KOR3010,중세국어강독,이지영,"2024-1, 2025-1"
20,KOR3208,문학과문화,"김예람, 박미란","2023-1, 2024-1, 2025-1, 2026-1"
21,KOR3213,문학과 융합적 상상력,이정원,"2023-2, 2025-1"
22,KOR3300,고전문학사,최지혜,"2023-1, 2024-1, 2025-1, 2026-1"
23,KOR3301,고전시텍스트읽기,최지혜,"2023-1, 2024-1, 2025-1, 2026-1"
24,KOR3307,고전소설론,이정원,"2023-1, 2025-1"
25,KOR3315,설화 문학의 이해,황윤정,2025-1
26,KOR4400,현대문학연습,박슬기,"2023-2, 2025-1"
27,KOR4503,디지털인문학강독,이정훈,"2024-1, 2025-1"
28,KORQ981,국어교과교육론,주세형,"2023-1, 2024-1, 2025-1"
29,KOR3004,국어형태론,"전지영, 황화상","2023-1, 2024-1, 2025-2, 2026-1"
30,KOR3304,한문과한문학,"백진우, 이채은","2023-1, 2025-2"
31,KOR3401,현대시텍스트읽기I,박슬기,2023-1
32,KOR4506,출판문화기획(캡스톤디자인),박슬기,2023-1
35,KOR3406,현대소설텍스트읽기II,김경수,"2024-1, 2025-2"
38,KOR4001,국어학연습,"김한별, 황화상","2024-1, 2025-2"
39,KOR4099,개별연구논문,"박슬기, 백진우","2025-2, 2026-1"
42,KOR3203,구비문학론,황윤정,2024-1
43,KOR3205,문장과수사,"우찬제, 장서란","2024-1, 2026-1"
44,KOR3214,전공진로설계Ⅰ,"김경수, 박슬기, 이정훈, 황윤정",2024-1
45,KOR3303,고전수필론,백진우,"2024-1, 2026-1"
46,KOR3405,현대시텍스트읽기II,박슬기,2024-1
48,KOR3302,고전소설텍스트읽기,이정원,"2023-2, 2026-1"
50,KOR3409,현대소설론,김경수,"2023-2, 2026-1"
54,KOR3018,국어통사론,이정훈,2026-1
55,KOR3408,현대시론,박슬기,2026-1

#### 4-2-3. 경제

In [34]:
make_major_dfs(df_all, major_name="eco", prefix="ECO")

In [35]:
df_eco_spring
#df_eco_summer
#df_eco_fall
#df_eco_winter

,과목번호,과목명,교수,개설학기
0,ECO2001,경제학원론I,"Iris Haydar Doruk, 김경환, 김숙영, 김영철, 김진원, 김홍균, 손성빈, 신혜선, 안태현, 이재철, 이진권, 전현배, 주하연, 허정","2023-1, 2023-2, 2023-summer, 2023-winter, 2024-1, 2024-2, 2024-summer, 2024-winter, 2025-1, 2025-2, 2025-summer, 2025-winter, 2026-1"
1,ECO2002,경제학원론II,"곽노선, 김경환, 김숙영, 김재호, 김형욱, 송의영, 우수경, 전현배, 정국모, 허준영","2023-1, 2023-2, 2023-summer, 2023-winter, 2024-1, 2024-2, 2024-summer, 2024-winter, 2025-1, 2025-2, 2025-summer, 2025-winter, 2026-1"
2,ECO2003,경제수리기초,"김인경, 김형욱, 박경옥, 이강오","2023-1, 2023-2, 2023-summer, 2024-1, 2024-2, 2024-summer, 2025-1, 2025-2, 2025-summer, 2026-1"
3,ECO2004,경제통계학,"김세진, 김인경, 박경옥, 백예인, 사공용, 오민석, 이성원, 이영훈, 주하연","2023-1, 2023-2, 2023-winter, 2024-1, 2024-2, 2024-winter, 2025-1, 2025-2, 2025-winter, 2026-1"
4,ECO2006,미시경제학I,"Iris Haydar Doruk, 김도영, 김인경, 김형욱, 왕규호, 이강오, 이진권, 주하연","2023-1, 2023-2, 2024-1, 2024-2, 2025-1, 2025-2, 2026-1"
5,ECO2007,거시경제학I,"곽노선, 곽준희, 김숙영, 김형욱, 남주하, 이윤수, 정국모, 조윤호, 허준영","2023-1, 2023-2, 2024-1, 2024-2, 2025-1, 2025-2, 2026-1"
7,ECO2009,계량경제학I,"김재호, 남준우, 백예인, 이성원, 이영훈, 이한식","2023-1, 2023-2, 2024-1, 2024-2, 2025-1, 2025-2, 2026-1"
8,ECO3001,산업경제학,"전현배, 주하연","2023-1, 2023-2, 2024-1, 2024-2, 2025-1, 2025-2, 2026-1"
10,ECO3008,금융경제학,"곽노선, 남주하","2023-1, 2024-1, 2024-2, 2025-2, 2026-1"
11,ECO3010,국제무역론,"송의영, 허정","2023-1, 2023-2, 2024-1, 2024-2, 2025-2, 2026-1"
12,ECO3011,국제금융론,"곽준희, 김윤정","2023-1, 2023-2, 2024-1, 2024-2, 2025-2"
13,ECO3017,국제경제학,"곽준희, 김윤정","2023-1, 2023-2, 2024-1, 2024-2, 2025-1, 2026-1"
14,ECO3022,금융시장의빅데이터분석(캡스톤디자인),정재식,"2023-2, 2024-2, 2025-2, 2026-1"
15,ECO3027,전공진로설계Ⅰ,"Iris Haydar Doruk, 곽준희, 김윤정, 김재호, 남주하, 전성훈, 정국모, 허준영","2024-1, 2024-2"
18,ECO4006,정보경제학,김도영,"2023-1, 2024-1, 2024-2, 2025-2"
20,ECO4030,행동경제학,Iris Haydar Doruk,"2024-2, 2025-1, 2025-2, 2026-1"
23,ECO4037,주식및채권시장,손성빈,"2023-1, 2024-1, 2024-2, 2025-2"
26,ECOG010,고급미시경제학I,"Iris Haydar Doruk, 이진권","2023-1, 2023-2, 2024-1, 2024-2, 2025-1, 2025-2, 2026-1"
27,ECOG020,고급거시경제학I,"곽준희, 이윤수, 조윤호, 허준영","2023-1, 2023-2, 2024-1, 2024-2, 2025-1, 2025-2, 2026-1"
28,ECOG030,고급계량경제학I,"백예인, 이성원, 이영훈","2023-1, 2023-2, 2024-1, 2024-2, 2025-1, 2025-2, 2026-1"
30,ECOG051,AI와빅데이터를활용한경제정보처리,양현주,"2023-1, 2024-2, 2025-1, 2025-2, 2026-1"
31,ECO2012,동태계획법,정국모,"2023-1, 2024-1, 2025-1, 2026-1"
32,ECO3012,개발경제학,양현주,"2023-1, 2025-1, 2026-1"
33,ECO3021,경제성장론,송의영,"2023-1, 2024-1, 2025-1, 2026-1"
34,ECO3023,AI금융(캡스톤디자인),정재식,"2023-1, 2024-1, 2025-1, 2026-1"
35,ECO3026,교통경제학,김진원,"2023-1, 2024-1, 2025-1, 2026-1"
36,ECO4004,경제수리통계학,"남준우, 이성원","2023-1, 2025-1, 2026-1"
37,ECO4005,게임이론,왕규호,"2023-1, 2024-1, 2025-1, 2026-1"
38,ECO4007,"경쟁법과산업규제의경제학, 독점규제의 경제학","김도영, 전성훈","2024-1, 2025-1, 2026-1"
39,ECO4008,금융정책,"남주하, 허준영","2023-1, 2023-2, 2024-1, 2025-1, 2025-2, 2026-1"
40,ECO4010,국제금융시장,박정수,"2023-1, 2024-1, 2025-1"
41,ECO4020,경제학특강3,김홍균,"2025-1, 2025-2"
42,ECO4032,금융시장계량분석(캡스톤디자인),김재호,"2023-1, 2024-1, 2025-1"
43,ECOG040,고급수리통계학,"이성원, 최인","2023-1, 2024-1, 2025-1, 2026-1"
44,ECO3002,노동경제학,안태현,"2023-1, 2023-2, 2024-1, 2025-2, 2026-1"
45,ECO3009,공공경제학,"김홍균, 조윤호","2023-1, 2024-1, 2026-1"
46,ECO3024,경제학도를위한파이썬,이강오,2023-1
47,ECO4009,파생상품시장,사공용,2023-1
52,ECO4022,경제학특강5,이강오,2024-1
54,ECO2013,경제학도를 위한 머신러닝과 AI,오민석,2026-1
55,ECOG121,고급기후환경경제학,신혜선,2026-1

#### 4-2-4. 수학

In [36]:
make_major_dfs(df_all, major_name="mat", prefix="MAT")

In [37]:
df_mat_spring
#df_mat_summer
#df_mat_fall
#df_mat_winter

,과목번호,과목명,교수,개설학기
1,MAT2010,집합론,"김순영, 김현석, 남선영, 박준용, 신창언, 이종범, 하구용","2023-1, 2023-2, 2023-summer, 2023-winter, 2024-1, 2024-2, 2024-summer, 2024-winter, 2025-1, 2025-2, 2025-summer, 2025-winter, 2026-1"
2,MAT2110,선형대수학,"강유태, 김대욱, 김준태, 박준용, 안소영, 옥지훈, 이영란, 임경필, 조상현, 조성희, 조장현, 최미란, 최승일, 한상현","2023-1, 2023-2, 2023-summer, 2023-winter, 2024-1, 2024-2, 2024-summer, 2024-winter, 2025-1, 2025-2, 2025-summer, 2025-winter, 2026-1"
7,MAT3020,통계학입문,"임경수, 임경필","2023-1, 2023-2, 2023-summer, 2023-winter, 2024-1, 2024-2, 2024-summer, 2024-winter, 2025-1, 2025-2, 2025-summer, 2026-1"
12,MAT3451,전공진로설계Ⅰ,"김종락, 김종수, 김준태, 신창언, 오영탁, 이재성, 임경수","2024-1, 2024-2"
18,MAT4510,학부개별연구,"김종락, 김현석","2023-2, 2024-1, 2024-2, 2026-1"
22,MAT1050,미적분학실습I,"김현석, 임경수","2023-1, 2024-1, 2025-1, 2026-1"
23,MAT2210,고등미적분학I,"김현석, 옥지훈, 이영란, 이재성","2023-1, 2024-1, 2025-1, 2026-1"
24,MAT2410,응용수학I,"김지현, 김현정, 안소영, 유지현, 이영록, 임경필","2023-1, 2023-winter, 2024-1, 2024-winter, 2025-1, 2025-winter, 2026-1"
25,MAT2510,푸리에해석및응용,임경수,"2023-1, 2024-1, 2025-1, 2026-1"
26,MAT3110,이산수학,"조성희, 조창연, 최승일","2023-1, 2024-1, 2025-1, 2026-1"
27,MAT3430,응용통계학및실습,"김대욱, 임경필","2023-1, 2024-1, 2025-1, 2025-winter, 2026-1"
28,MAT3440,통신수학,김종락,"2024-1, 2025-1"
29,MAT4110,추상대수학I,"김종락, 오영탁, 조창연","2023-1, 2024-1, 2025-1, 2026-1"
30,MAT4210,복소수함수론I,"이재성, 정순영","2023-1, 2024-1, 2025-1, 2026-1"
31,MAT4310,미분기하학,"강유태, 김종수, 김준태","2023-1, 2024-1, 2025-1, 2026-1"
32,MAT4330,위상수학개론II,"김준태, 조장현","2023-1, 2024-1, 2025-1, 2026-1"
33,MATG210,실변수함수론,"이영란, 이재성","2023-1, 2024-1, 2025-1, 2026-1"
34,MATQ981,수학교과교육론,김구연,"2023-1, 2024-1, 2025-1, 2026-1"